include:
   - project: cells/ci
     file: /ci/lib/common.yml

feature-extraction-docker:
  before_script:
  - !reference [.docker, load-python-39]
  script:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - cd feature_extraction
  - pytest -sx tests

optimization-docker:
  before_script:
  - !reference [.docker, load-python-39]
  script:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - cd optimization
  - nrnivmodl opt_module/mechanisms
  - pytest -sx tests

model-management-docker:
  before_script:
  - !reference [.docker, load-python-39]
  script:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - cd model_management/mm_run_minimal
  - pytest -sx tests

validation-docker:
  before_script:
  - !reference [.docker, load-python-39]
  script:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - cd validation
  - nrnivmodl mechanisms
  - pytest -sx tests
