name: Create diagram
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - viz
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".gitignore,.gitattributes,.github,feature_extraction/input-traces,validation/input/morphologies"
          file_colors: '{"json": "#fda7df", "mod": "#e43131", "yml": "#8d31e4", "ini": "#badc58", "dat": "#f3d44e", "xml": "#905614", "md" : "#f2346e", "asc": "#74e2c9"}'
