name: Release

on:
  push:
    branches:
      - main

jobs:
  call-test-workflow:
    uses: BlueBrain/SSCxEModelExamples/.github/workflows/python-app.yml@main

  build-and-publish:
    name: Build and make a GitHub release
    runs-on: ubuntu-latest
    needs: call-test-workflow
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Fetch the tag, if any. If not tagged, create a patch tag
        uses: anothrNick/github-tag-action@1.64.0
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        id: tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch

      - name: Get and store the latest tag
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=${{ steps.tag.outputs.new_tag }}" >> $GITHUB_ENV
      - name: Get and store tag from triggered tag push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          generate_release_notes: true
